"""演示数据快照 —— **由 scripts/export_seed_snapshot.py 从真实数据库导出**，不要手写。

seed.py 读这份数据把空库灌成与导出时**完全一致**的状态。
日期全部是绝对日期（已冻结），所以换一天跑结果也一样。

想改演示数据：先把库调成想要的样子，再跑
    cd backend && ./.venv/bin/python scripts/export_seed_snapshot.py
重新导出即可。

三处无法逐字复现（只能语义一致）：
  1. 密码哈希 —— bcrypt 每次加盐不同，统一用 INITIAL_PASSWORD
  2. 附件存储名 —— uuid 每次不同；界面显示的原始文件名一致
  3. 自增 id —— 按插入顺序重新分配（关系正确，数值可能不同）
"""

# 年级（按原 id 顺序，保证新库里 id 也对得上）
GRADES = [
    '2024级',
    '2025级',
    '2026级',
]

# 账号：老师排在第一，其余按原 id 顺序
USERS = [
    {
        'username': 'teacher',
        'name': '曾明伟',
        'role': 'teacher',
        'student_no': None,
        'grade': None,
    },
    {
        'username': 'liuwenqiang',
        'name': '刘文强',
        'role': 'student',
        'student_no': '2024001',
        'grade': '2024级',
    },
    {
        'username': 'liuzilong',
        'name': '刘子龙',
        'role': 'student',
        'student_no': '2024002',
        'grade': '2024级',
    },
    {
        'username': 'yanglei',
        'name': '杨磊',
        'role': 'student',
        'student_no': '2024003',
        'grade': '2024级',
    },
    {
        'username': 'liufuqiang',
        'name': '刘富强',
        'role': 'student',
        'student_no': '2025001',
        'grade': '2025级',
    },
    {
        'username': 'panyouqi',
        'name': '潘有琪',
        'role': 'student',
        'student_no': '2025002',
        'grade': '2025级',
    },
    {
        'username': 'tongjian',
        'name': '童健',
        'role': 'student',
        'student_no': '2025003',
        'grade': '2025级',
    },
    {
        'username': 'zhangchenghe',
        'name': '张成赫',
        'role': 'student',
        'student_no': '2025004',
        'grade': '2025级',
    },
    {
        'username': 'yangkang',
        'name': '杨康',
        'role': 'student',
        'student_no': '2026001',
        'grade': '2026级',
    },
    {
        'username': 'xiexundong',
        'name': '谢循东',
        'role': 'student',
        'student_no': '2026002',
        'grade': '2026级',
    },
    {
        'username': 'fengcheng',
        'name': '冯成',
        'role': 'student',
        'student_no': '2026003',
        'grade': '2026级',
    },
]

# 论文项目（含 8 节点 × 2 轨道的完整里程碑）
PROJECTS = [
    {
        'student': 'yanglei',
        'title': '',
        'stage': '开题',
        'progress': 65,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
    {
        'student': 'liufuqiang',
        'title': '',
        'stage': '开题',
        'progress': 22,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
    {
        'student': 'panyouqi',
        'title': '',
        'stage': '开题',
        'progress': 29,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
    {
        'student': 'tongjian',
        'title': '',
        'stage': '开题',
        'progress': 22,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
    {
        'student': 'zhangchenghe',
        'title': '',
        'stage': '开题',
        'progress': 15,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
    {
        'student': 'yangkang',
        'title': '',
        'stage': '开题',
        'progress': 0,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
    {
        'student': 'xiexundong',
        'title': '',
        'stage': '开题',
        'progress': 0,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
    {
        'student': 'fengcheng',
        'title': '',
        'stage': '开题',
        'progress': 0,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
    {
        'student': 'liuwenqiang',
        'title': '面向边缘计算的轻量级模型压缩方法研究',
        'stage': '初稿',
        'progress': 57,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': '2026-05-10',
                'actual': '2026-05-08',
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': '2026-07-15',
                'actual': '2026-07-18',
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': '2026-09-25',
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': '2026-12-01',
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': '2026-11-10',
                'actual': None,
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': '2026-12-20',
                'actual': None,
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
    {
        'student': 'liuzilong',
        'title': '知识图谱驱动的智能问答系统设计与实现',
        'stage': '修改',
        'progress': 57,
        'risk_override': None,
        'milestones': [
            {
                'key': 'p1-0',
                'label': '学基础',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-1',
                'label': '看论文',
                'track': 1,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-2',
                'label': '出想法',
                'track': 1,
                'plan': '2026-04-20',
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-3',
                'label': '写论文',
                'track': 1,
                'plan': '2026-06-20',
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-4',
                'label': '改论文',
                'track': 1,
                'plan': '2026-08-01',
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-5',
                'label': '已投稿',
                'track': 1,
                'plan': '2026-11-20',
                'actual': '2026-09-14',
            },
            {
                'key': 'p1-6',
                'label': '修论文',
                'track': 1,
                'plan': '2026-10-15',
                'actual': None,
            },
            {
                'key': 'p1-7',
                'label': '中论文',
                'track': 1,
                'plan': '2026-12-19',
                'actual': None,
            },
            {
                'key': 'p2-0',
                'label': '学基础',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-1',
                'label': '看论文',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-2',
                'label': '出想法',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-3',
                'label': '写论文',
                'track': 2,
                'plan': None,
                'actual': '2026-09-14',
            },
            {
                'key': 'p2-4',
                'label': '改论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-5',
                'label': '已投稿',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-6',
                'label': '修论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
            {
                'key': 'p2-7',
                'label': '中论文',
                'track': 2,
                'plan': None,
                'actual': None,
            },
        ],
    },
]

# 演示附件的正文：原始文件名 → 内容
ATTACHMENTS = {
    '开题报告_V2.pdf': '%PDF-1.4\n演示附件：刘文强 开题报告 V2\n',
    '开题报告_V2_批注版.pdf': '%PDF-1.4\n演示附件：开题报告 V2 批注版（红笔批注）\n',
    '论文初稿_前三章.pdf': '%PDF-1.4\n演示附件：刘文强 论文初稿（前三章）\n',
    '中期检查材料.pdf': '%PDF-1.4\n演示附件：刘子龙 中期检查材料\n',
    '中期材料_批注版.pdf': '%PDF-1.4\n演示附件：中期材料 批注版\n',
    '中期材料_V2.pdf': '%PDF-1.4\n演示附件：刘子龙 中期材料 V2\n',
}

# 多轮往返（student_submitted_at / feedback_at 为绝对时间）
ROUNDS = [
    {
        'student': 'liuwenqiang',
        'round_no': 1,
        'student_text': '老师好，这是我修改后的开题报告，已按意见聚焦到「端侧模型剪枝」这一条线，技术路线重写了第三章，麻烦您再看一下。',
        'student_file': '开题报告_V2.pdf',
        'teacher_comment': '聚焦后的方向可行，可以往下做。补充一点：第三章的实验环境要把数据集规模、硬件型号写清楚，方便复现。',
        'teacher_file': '开题报告_V2_批注版.pdf',
        'submitted_at': '2026-07-18 14:20:00.000000',
        'feedback_at': '2026-07-21 09:30:00.000000',
    },
    {
        'student': 'liuwenqiang',
        'round_no': 2,
        'student_text': '已补上实验环境的硬件与数据说明，并把剪枝比例做成参数化配置。初稿前面三章写完了，先发您过一遍。',
        'student_file': '论文初稿_前三章.pdf',
        'teacher_comment': '写的不错，以后不要再写了',
        'teacher_file': None,
        'submitted_at': '2026-09-09 14:20:00.000000',
        'feedback_at': '2026-09-12 12:40:17.525655',
    },
    {
        'student': 'liuzilong',
        'round_no': 1,
        'student_text': '老师，中期材料先发您：平台原型跑通了问答主流程，接口文档和数据字典见附件。',
        'student_file': '中期检查材料.pdf',
        'teacher_comment': '进度说明和实物证据对不上：原型只有首页能点，图谱构建那部分没有截图。请补开发日志和数据库 ER 图再交一次。',
        'teacher_file': '中期材料_批注版.pdf',
        'submitted_at': '2026-08-01 14:20:00.000000',
        'feedback_at': '2026-08-04 09:30:00.000000',
    },
    {
        'student': 'liuzilong',
        'round_no': 2,
        'student_text': '补充了开发日志（Git 提交记录导出）和 ER 图，问答模块的召回率测试也在附录里。',
        'student_file': '中期材料_V2.pdf',
        'teacher_comment': None,
        'teacher_file': None,
        'submitted_at': '2026-09-06 14:20:00.000000',
        'feedback_at': None,
    },
]

# 周报
REPORTS = [
    {
        'student': 'liuwenqiang',
        'week': '2026-W37',
        'content_md': '## 本周进展\n- 完成 **前三章初稿**，共 41 页\n- 把剪枝比例做成参数化配置，跑了 3 组对照\n## 遇到问题\n- 边缘设备上的量化精度掉得比预期多，正在排查\n## 下周计划\n- 补齐消融实验，重写第四章\n## 本周进展\n- 完成 **前三章初稿**，共 41 页\n- 把剪枝比例做成参数化配置，跑了 3 组对照\n## 遇到问题\n- 边缘设备上的量化精度掉得比预期多，正在排查\n## 下周计划\n- 补齐消融实验，重写第四章',
        'created_at': '2026-09-13 20:15:00.000000',
        'updated_at': '2026-09-12 13:03:39.542819',
    },
    {
        'student': 'liuwenqiang',
        'week': '2026-W36',
        'content_md': '## 本周进展\n- 整理实验环境说明与数据集统计表\n- 重写第三章技术路线\n## 下周计划\n- 开始写初稿前两章',
        'created_at': '2026-09-06 20:15:00.000000',
        'updated_at': '2026-09-12 10:49:07.314112',
    },
    {
        'student': 'liuwenqiang',
        'week': '2026-W35',
        'content_md': '## 本周进展\n- 按批注意见修改开题报告\n- 补充近两年顶会文献 9 篇\n## 下周计划\n- 完成开题报告终稿',
        'created_at': '2026-08-30 20:15:00.000000',
        'updated_at': '2026-09-12 10:49:07.315074',
    },
    {
        'student': 'liuwenqiang',
        'week': '2026-W34',
        'content_md': '## 本周进展\n- 完成开题报告初稿\n- 与小组成员讨论技术路线\n## 下周计划\n- 等老师批注后修改',
        'created_at': '2026-08-23 20:15:00.000000',
        'updated_at': '2026-09-12 10:49:07.315767',
    },
    {
        'student': 'liuzilong',
        'week': '2026-W37',
        'content_md': '## 本周进展\n- 补开发日志与 ER 图\n- 跑通问答召回率测试，Top5 命中 71%\n## 遇到问题\n- 实体链接在长尾实体上错误率偏高\n## 下周计划\n- 优化实体链接，准备初稿',
        'created_at': '2026-09-13 20:15:00.000000',
        'updated_at': '2026-09-12 10:49:07.335571',
    },
    {
        'student': 'liuzilong',
        'week': '2026-W35',
        'content_md': '## 本周进展\n- 搭建问答主流程原型**（仅首页可点，未完成）**\n## 说明\n- 中期材料准备仓促，部分截图未补',
        'created_at': '2026-08-30 20:15:00.000000',
        'updated_at': '2026-09-12 10:49:07.336529',
    },
]

# 周报点评
REPORT_COMMENTS = [
    {
        'student': 'liuwenqiang',
        'week': '2026-W37',
        'author': 'teacher',
        'content': '收到。精度下降那组把中间层激活值分布画出来看看，下周三组会讲讲。',
        'created_at': '2026-09-14 09:20:00.000000',
    },
    {
        'student': 'liuwenqiang',
        'week': '2026-W36',
        'author': 'teacher',
        'content': '进度正常，保持。',
        'created_at': '2026-09-07 09:20:00.000000',
    },
    {
        'student': 'liuzilong',
        'week': '2026-W37',
        'author': 'teacher',
        'content': '开发日志这次补得完整。初稿 Deadline 在 10 月中旬，按现在的进度要压缩写作时间，建议本周把大纲先发我。',
        'created_at': '2026-09-14 09:20:00.000000',
    },
]

# 问答主贴
QUESTIONS = [
    {
        'author': 'liuwenqiang',
        'content': '请问学校图书馆的查重入口在哪里？第一次提交查重需要注意什么？',
        'created_at': '2026-09-10 15:40:00.000000',
    },
    {
        'author': 'liuzilong',
        'content': '中期检查可以用之前开题的材料吗？还是有规定的新模板？',
        'created_at': '2026-09-10 15:40:00.000000',
    },
]

# 问答回复（question 是 QUESTIONS 里的下标）
REPLIES = [
    {
        'question': 0,
        'author': 'teacher',
        'content': '图书馆主页右下角「学位论文查重」入口，用学号登录。第一次提交记得把致谢和附录一起删掉再传。',
        'created_at': '2026-09-10 18:05:00.000000',
    },
]

# 公告
ANNOUNCEMENTS = [
    {
        'author': 'teacher',
        'title': '中期检查安排',
        'content': '各位同学：中期检查定于本月 20 日下午 2 点在实验楼 301 进行，请提前准备好中期报告和演示材料。',
        'created_at': '2026-09-11 13:08:25.881527',
    },
]

# 常用链接
LINKS = [
    {
        'title': '学校图书馆',
        'url': 'https://lib.ahu.edu.cn/',
        'created_by': 'teacher',
    },
    {
        'title': '知网',
        'url': 'https://www.cnki.net/',
        'created_by': 'teacher',
    },
]

# 风险基准配置（与 Setting 表里的一致）
RISK_CONFIG = {
    'anchor_month': 9,
    'baselines': {
        'paper1': {
            '学基础': None,
            '看论文': None,
            '出想法': 12,
            '写论文': 14,
            '改论文': 16,
            '已投稿': 18,
            '修论文': None,
            '中论文': None,
        },
        'paper2': {
            '学基础': None,
            '看论文': None,
            '出想法': 20,
            '写论文': 22,
            '改论文': 23,
            '已投稿': 24,
            '修论文': None,
            '中论文': None,
        },
    },
}

